POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "12345678",
  "phone": "0123456789",
  "role": "customer",
  "image_url": "https://example.com/avatar.jpg"
}
