POST http://localhost:81/api/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "12345678",
  "phone": "0123456789",
  "role": "user",
  "image_url": "https://example.com/avatar.jpg"
}
